#!/bin/sh
new_mail() {
	notmuch search tag:unread 2>/dev/null | wc -l
}

music() {
	info=$(cmus-remote -Q 2>/dev/null | grep '\(title\|artist\)' | head -2 | sed 's/^.*\(artist\|title\) //')
	IFS='
	'
	set -- $info
	[ ! -z "$info" ] && echo " [$1] $2 |"
	unset IFS
}

while true; do
	xsetroot -name "$(music)  $(new_mail) | $(date +'%a %d/%m/%y %H:%M') "
	sleep 10
done
