set-option global indentwidth 0
set-option global ui_options terminal_status_on_top=true

colorscheme gruvbox-dark
face global comment "rgb:928374+a" # Why don't comments have a sane background?

# Transparent background
face global Default "rgb:ebdbb2,default"
face global BufferPadding "rgb:ebdbb2,default"

evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
    	git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}

plug "andreyorst/plug.kak" noload
plug "alexherbo2/auto-pairs.kak" config %{
	enable-auto-pairs
}
plug "andreyorst/smarttab.kak" defer smarttab %{
	set-option global softtabstop 4
} config %{
	hook global WinSetOption filetype=(rust|markdown|kak|lisp|scheme|sh|perl) expandtab
	hook global WinSetOption filetype=(makefile|gas) noexpandtab
	hook global WinSetOption filetype=(c|cpp) smarttab
}
plug "andreyorst/fzf.kak"
plug "ftonneau/digraphs.kak" %{
	set-option global digraphs_path 'plugins/digraphs.kak'
	digraphs-enable-on '<a-k>' '<c-k>'
}
plug "andreyorst/powerline.kak" defer powerline_gruvbox %{
	powerline-theme gruvbox
} config %{
	powerline-start
}
evaluate-commands %sh{
	command -v kak-lsp >/dev/null || st -e doas xbps-install -y kak-lsp
	kak-lsp --kakoune -s $kak_session
}
hook global WinSetOption filetype=(go|c|cpp|rust) %{
	lsp-enable-window
	lsp-auto-signature-help-enable
	map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
}

hook global WinSetOption filetype=rust %{
	set-option window indentwidth 4
}

map global user . ': fzf-mode<ret>' -docstring "Run fzf"
map global user w ': w<ret>' -docstring "Save"
map global user , ': wq<ret>' -docstring "Save and quit"
map global user f '{p|fmt<ret>' -docstring "Format paragraph"
