#!/bin/sh

#Autostart
source $HOME/.xsession
killall sxhkd ; sxhkd &
killall picom ; picom -i 0.6 &
#hsetroot -cover ~/.config/wall.jpg &
nitrogen --set-zoom-fill --random $HOME/Media/Pictures/wallpapers/Planets/
$HOME/.config/bspwm/scripts/panel.sh &

##Kill all istances of cleanfullscreen
for x in $(pstree -p | grep "cleanfullscreen" | awk -F\( '{print $2}' | sed 's/.$//g'); do
	kill $x
done
$HOME/.config/bspwm/scripts/cleanfullscreen.sh &

# Workspaces
bspc monitor -d          
# Set master and stack layout on every workspace
#for x in $(cat $HOME/.config/bspwm/tags.txt); do
#	bsp-layout set tall $x -- --master-size 0.5
#done

##
bspc config border_width 1
bspc config window_gap 20
bspc config top_padding 20
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config click_to_focus none

#Theme
bspc config normal_border_color '#000000'
bspc config active_border_color '#ffffff'
bspc config focused_border_color '#d62e3f'
bspc config borderless_monocle false
bspc config presel_feedback false


#Rules
bspc rule -a Firefox desktop='^3' focus=on follow=on
bspc rule -a mpv desktop='^9' focus=on follow=on
bspc rule -a Neomutt desktop='^5' focus=on follow=on
bspc rule -a Calcurse desktop='^7' focus=on follow=on
bspc rule -a mocp desktop='^8' focus=on follow=on
bspc rule -a Lxappearance state=floating
bspc rule -a Vifm desktop='^2' focus=on follow=on
bspc rule -a Pcmanfm desktop='^2' focus=on follow=on
bspc rule -a Pavucontrol desktop='^10' focus=on follow=on
bspc rule -a newsboat desktop='^4' focus=on follow=on
bspc rule -a 'Tor Browser' desktop='^3' focus=on follow=on
bspc rule -a TelegramDesktop desktop='^6' focus=on follow=on
bspc rule -a Signal desktop='^6' focus=on follow=on
bspc rule -a Zathura focus=on state=tiled
