#!/bin/bash
# MIT/X Consortium License

# © 2021 Mario Forzanini <mario.forzanini@studenti.unimi.it>

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

file=$(ls /home/mario/Documents/Personal/Bilancio | dmenu -i -p "Calcola il bilancio:")
tot=0
entrate=0
uscite=0

operazione=$(echo -e "Dettagli\nEntrate\nGuadagno\nSpese" | dmenu -i -p "Bilancio:")

case $operazione in
	"Dettagli") date=$(awk '{print $1}' $file | dmenu -i -p "Data:")
		spesa=$(awk '{print $2}' $file)
		causale=$(awk '{print $3}' $file)
		notify-send "$date" "$spesa $causale"
		;;
	"Entrate") for x in $(awk '/\+/ {print $2}' $file | sed 's/\+//g'); do
		((entrate+=x))
	done
	notify-send "$entrate"
	;;
	"Guadagno") for x in $(awk '/\+/ {print $2}' $file | sed 's/\+//g'); do
		((entrate+=x))
	done
	for x in $(awk '/\-/ {print $2}' $file | sed 's/\-//g'); do
		((uscite-=x))
	done
	((tot=$entrate-$uscite))
	notify-send "$tot"
	;;
	"Spese") for x in $(awk '/\-/ {print $2}' $file | sed 's/\-//g'); do
		((uscite-=x))
	done
	notify-send "$uscite"
	;;
	*);;
esac

