#!/bin/sh
# Using luke smith's emoji file copy unicode char to clipboard

chosen=$(cut -d\; -f1 <$HOME/.local/share/emoji | dmenu -i -l 20 -p "Choose emoji: " | sed 's/ .*//')

test -z "$chosen" && exit

printf "$chosen" | xclip -selection clipboard
